
# Path to your oh-my-zsh installation.
export ZSH="/Users/bernardocasaleiro/.oh-my-zsh"

# oh-my-zsh theme.
ZSH_THEME="robbyrussell"

# Case-sensitive completion.
CASE_SENSITIVE="true"

# Set fzf installation directory path
export FZF_BASE=/usr/local/opt/fzf

# Plugins
plugins=(
  git
  docker
  fzf
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Aliases
alias ll="ls -la"
alias vim="nvim"
alias d="docker"
alias dc="docker-compose"
